language: generic
sudo: required

services:
    - docker

before_install:
  - sudo apt-get -y install curl p7zip-full

script:
    - sudo ./build.sh
    - docker import sdk.tar sailfishos-platform-sdk
    - ./test.sh
